# Generated by Django 3.1.5 on 2022-06-19 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-updated']},
        ),
    ]
